### ISSUE TITLE
eth.hyperverse.dev

### ISSUE THREAD

**Issue by ShainDholakiya** [decentology/hyperverse-docs#55]
another path that shows to go to eth.hyperverse.dev and what that entails (UI creating a tenant, cloning a blank template, storybook, etc.)

**Comment by joenyzio** [comment]
I need to fix the panel

**Comment by joenyzio** [comment]
Left as is. INFO box leads to the other page to show Ethereum UI and the panels lead to sections for create-next-app and using monorepo within the same page.
